// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtQWPWpBnCY8NfRausAK2XlhsvVg4iwqg',
    appId: '1:860878388510:web:599d587203d53aa240dd0f',
    messagingSenderId: '860878388510',
    projectId: 'learning-firebase-bddb1',
    authDomain: 'learning-firebase-bddb1.firebaseapp.com',
    storageBucket: 'learning-firebase-bddb1.firebasestorage.app',
    measurementId: 'G-SYJSPM0TMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMJqiCLP_H3rcUHSTySCCAsX0qP1m2qeA',
    appId: '1:860878388510:android:d8f2a00fc2abdd6240dd0f',
    messagingSenderId: '860878388510',
    projectId: 'learning-firebase-bddb1',
    storageBucket: 'learning-firebase-bddb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVhoZr7AdnwubrVqwLibX4fTh-s5mmL5c',
    appId: '1:860878388510:ios:4829113a43f273f740dd0f',
    messagingSenderId: '860878388510',
    projectId: 'learning-firebase-bddb1',
    storageBucket: 'learning-firebase-bddb1.firebasestorage.app',
    iosBundleId: 'com.example.myStyleApp',
  );
}
